### ISSUE TITLE
Can`t use navigation with Navmeshes for isometric map

### ISSUE THREAD

**Issue by YegorStolyarov** [Seldom-SE/seldom_map_nav#1]
Thank you for the great plugin!
The problem is that ```Navmeshes::generate()``` returns Navmeshes bound to square topdown map.
I have no idea how to use it with isometric map. 
If I could pass a Square-to-Iso translation function, as argument to ```Navmeshes::generate()```, or just a map_type, that would help me a lot.
Pathfinding seems to work fine, but it receives squared-tile collisions info from NavMeshes
Any advice for workaround this problem will also be accepted.

**Comment by Seldom-SE** [comment]
You can use [`seldom_interop`](https://github.com/Seldom-SE/seldom_interop) to separate your coordinate systems. So, implement `Position2` for some type and add a `MapNavPlugin<MyPosition2Type>` instead of `MapNavPlugin<Transform>` (which is the default). Then, you can apply the square-to-iso translation each frame.

**Comment by YegorStolyarov** [comment]
> You can use [`seldom_interop`](https://github.com/Seldom-SE/seldom_interop) to separate your coordinate systems. So, implement `Position2` for some type and add a `MapNavPlugin<MyPosition2Type>` instead of `MapNavPlugin<Transform>` (which is the default). Then, you can apply the square-to-iso translation each frame.

after several hours it worked!
```
// first i wrote minimalistic type for Vec2:
#[derive(Component)]
struct Transform2(Vec2);

impl Position2 for Transform2 {
    type Position = Vec2;

    fn get(&self) -> Self::Position {
        self.0
    }

    fn set(&mut self, pos: Self::Position) { self.0 = pos }
}

// attached it to the app
.add_plugins(MapNavPlugin::<Transform2>::default())

// Also I used Navmeshes::generate() with custom square grid size, for easier conversion (turn right, then resizeY)
fn iso_to_nav_coord(v: Vec2) -> Vec2 {
    let angle_rad = 45_f32.to_radians();
    let new_x = v.x * angle_rad.cos() - v.y * angle_rad.sin() * 2.;
    let new_y = v.x * angle_rad.sin() + v.y * angle_rad.cos() * 2.;
    Vec2 { x: new_x, y: new_y }
}

// handling click on ground, converting world xy to navmap xy
          let square_coord = iso_to_nav_coord(cursor_pos);
            debug!("Square coords on NavMesh: {:?}", square_coord);

            commands.entity(players.single()).insert(NavBundle {
                pathfind: Pathfind::new(
                    navmesheses.single(),
                    8.,
                    None,
                    PathTarget::Static(square_coord),
                    NavQuery::Accuracy,
                    NavPathMode::Accuracy,
                ),
                nav: Nav::new(200.),
            });
          });

```

**Comment by YegorStolyarov** [comment]
while moving, converting hashmap coord to iso world coord in players Transform
```
fn nav_to_iso_coord(v: Vec2) -> Vec2 {
    let angle_rad = -45_f32.to_radians();
    let new_x = v.x * angle_rad.cos() - v.y * angle_rad.sin();
    let new_y = v.x * angle_rad.sin() + v.y * angle_rad.cos();
    Vec2 { x: new_x, y: new_y * 0.5}
}

fn translate_coords(
    // mut commands: Commands,
    mut players: Query<(&mut Transform, &Transform2), With<Player>>,
) {
   let (mut transform, transform2) = players.single_mut();
    let iso_pos = nav_to_iso_coord(transform2.0);
    transform.translation.x = iso_pos.x;
    transform.translation.y = iso_pos.y;
}
```

**Comment by YegorStolyarov** [comment]
Should I make an example from this? Howewer, bevy_ecs_map will be needed to draw iso map.
Maybe generating pure isometric NavMesher would be more effective, but I can`t consider if it easy or not.

I`m still experiencing small collision offsets, hope to fix it later : D

**Comment by Seldom-SE** [comment]
> Should I make an example from this?

I would appreciate it!
